### PR TITLE
Implement a port of the original Random Things overlay

### PR DESCRIPTION
**Pull request by unascribed**
image

I did this for someone else, but I figured I should PR it to here as well.

The original overlay is dynamically rendered(!) so I set up a shim dev env with 1.12 Random Things and convinced it to render the overlay flat to a black background:
image

I then saved these as 2048x2048 renders, scaled them down to 512x512, and removed the black background, creating the filmstrip that is "time_ring.png" in this PR.

I also changed the rotation rate to be independent of the speedup factor, as it was in the original Random Things version. It's unnecessary when the overlay texture changes to reflect higher speedups.

Something this loses out on is some subtle pulsing effects and a "spinning" effect on the outer ring, but I feel this version is "close enough" and can be refined later. It's a lot better than the current animation.

Random Things is under the MIT license, and how *output* from a computer program relates to its licensing is... fuzzy. At worst, we can consider these images to be under the same MIT license as the code, which should be acceptable.

### CODE REVIEW

**Comment by alkyaly** [comment]
This is amazing, thanks!
When I first tried to port the overlay, I tried to dynamically render it, it didn't go too well :joy:.
Would you like to be added to be added in the fabric.mod.json contributors?

**Comment by unascribed** [comment]
Welcome ^^

> Would you like to be added to be added in the fabric.mod.json contributors?

If you want; I'm not particularly attached to this and hardly deserve the credit, considering this is a straight rip of the original overlay by Lumien, and a very simple change to the renderer.

**Comment by alkyaly** [comment]
Mentioned in the changelog

**Comment by unascribed** [comment]
Here's a new video, if you want it.

GIF (high-quality, encoded with [Gifski](https://gif.ski): https://blob.jortage.com/blobs/f/bb2/fbb25fa65e044076fa1038b6ff35be223d87208c70ca82864694ea9aed6109af2a28e89dbaa8b22a111684ba513b369f7935a6d805561624222a4e852b15e49a

MP4: https://blob.jortage.com/blobs/0/04f/004f1799eea10f3660e0caee2ed77f394294878dc31021efb32fc94d2a38fc6912c42c11cd7e0f2e2bf8bab7b0088ae4aec58ab68c418dd556ecc74173c6eba2

These are hosted on Jortage, a CDN I run. You can link to them directly.

**Pull request merged**
